GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Test",
    "number": "100-200-3000"
}
###

DELETE  http://localhost:3001/api/persons/1
